language check - unsafe
Modified modules:
  RHEL6_7/backup/bacula
  RHEL6_7/backup/NoverifyConfigs
  RHEL6_7/backup/UntrackedFiles
  RHEL6_7/databases/mysql
  RHEL6_7/databases/mysql/configuration_changes
  RHEL6_7/databases/mysql/data_migration
  RHEL6_7/databases/mysql/general_changes
  RHEL6_7/databases/postgresql
  RHEL6_7/desktop/GNOME
  RHEL6_7/desktop/KDE
  RHEL6_7/drivers/ObsoletedGraphicDrivers
  RHEL6_7/drivers/ObsoletedInputDrivers
  RHEL6_7/drivers/ObsoletedNetworkDrivers
  RHEL6_7/drivers/ObsoletedStorageDrivers
  RHEL6_7/drivers/ObsoletePOWER6Processors
  RHEL6_7/networking/bind/bind-chroot
  RHEL6_7/networking/bind/configuration
  RHEL6_7/networking/dnsmasq
  RHEL6_7/networking/dovecot
  RHEL6_7/networking/iptables
  RHEL6_7/networking/net-snmp
  RHEL6_7/networking/nfsv2
  RHEL6_7/networking/openldap
  RHEL6_7/networking/openssh
  RHEL6_7/networking/openssh-keycat
  RHEL6_7/networking/postfix
  RHEL6_7/networking/RHDS
  RHEL6_7/networking/sendmail
  RHEL6_7/networking/squid
  RHEL6_7/networking/vsftpd
  RHEL6_7/others/configchanges
  RHEL6_7/others/NoVersionChangeEtc
  RHEL6_7/others/rsyslog
  RHEL6_7/others/vcsrepos
  RHEL6_7/packages/GenericUtilities
  RHEL6_7/packages/InterVariants
  RHEL6_7/packages/LoadBalanceSupport
  RHEL6_7/packages/NonRHSignedPkg
  RHEL6_7/packages/notbase-channel
  RHEL6_7/packages/ObsoletedPackages
  RHEL6_7/packages/ObsoletedW3m
  RHEL6_7/packages/pkgdowngrades
  RHEL6_7/packages/RemovedPackages
  RHEL6_7/packages/RemovedTaskjuggler
  RHEL6_7/packages/ReplacedPackages
  RHEL6_7/selinux/CustomPolicy
  RHEL6_7/selinux/general
  RHEL6_7/selinux/RestoreConfig
  RHEL6_7/selinux/samba
  RHEL6_7/services/cupsbrowsing
  RHEL6_7/services/httpd
  RHEL6_7/services/ipa/bind-dyndb-ldap
  RHEL6_7/services/ipa/ipa-server
  RHEL6_7/services/ipa/pki-ca
  RHEL6_7/services/ntp/configuration
  RHEL6_7/services/ntp/timesync
  RHEL6_7/services/openldap
  RHEL6_7/services/openssh/sshd
  RHEL6_7/services/quota_nld/configuration
  RHEL6_7/services/quota_nld/new_package
  RHEL6_7/services/sssd
  RHEL6_7/services/tomcat
  RHEL6_7/storage/cryptsetup-luks
  RHEL6_7/storage/multipath
  RHEL6_7/storage/tgtd
  RHEL6_7/storage/warnquota/configuration
  RHEL6_7/system/AddOns
  RHEL6_7/system/aide
  RHEL6_7/system/Architecture
  RHEL6_7/system/BinariesRebuild
  RHEL6_7/system/Debuginfo
  RHEL6_7/system/dts
  RHEL6_7/system/FHS/ReadOnlyFHS
  RHEL6_7/system/FHS/Run
  RHEL6_7/system/FHS/UsrPartition
  RHEL6_7/system/grub
  RHEL6_7/system/HA-Cluster/ha-cluster
  RHEL6_7/system/hal
  RHEL6_7/system/initscripts/control
  RHEL6_7/system/initscripts/ifcfg
  RHEL6_7/system/java
  RHEL6_7/system/kernel-kdump
  RHEL6_7/system/KrbMigration
  RHEL6_7/system/libcgroup
  RHEL6_7/system/pam
  RHEL6_7/system/PartitionMounts
  RHEL6_7/system/perl
  RHEL6_7/system/php
  RHEL6_7/system/polkit
  RHEL6_7/system/RemovableMedia
  RHEL6_7/system/repositories
  RHEL6_7/system/scl-collection
  RHEL6_7/system/SonameBump
  RHEL6_7/system/SonameKept
  RHEL6_7/system/SonameRemoval
  RHEL6_7/system/SysconfigCgroupDaemon
  RHEL6_7/system/SystemVersion
  RHEL6_7/system/tuned
  RHEL6_7/system/uefi
  RHEL6_7/system/yaboot
  RHEL6_7/system/yum
  RHEL6_7/usrmgmt/DangerousRanges
  RHEL6_7/usrmgmt/libuser
  RHEL6_7/usrmgmt/ReservedIDs
  RHEL6_7/usrmgmt/ypserv
  RHEL6_7/usrmgmt/ypserv/maps_dbm
  RHEL6_7/usrmgmt/ypserv/max_uid_gid

diff --git a/RHEL6_7/packages/ObsoletedPackages/check b/RHEL6_7/packages/ObsoletedPackages/check
--- a/RHEL6_7/packages/ObsoletedPackages/check
+++ b/RHEL6_7/packages/ObsoletedPackages/check
@@ -13,7 +13,7 @@ get_repo_id() {
 }
 
 [ ! -f "$VALUE_RPM_RHSIGNED" ] || [ ! -r "$COMMON_DIR" ] && {
-  log_error "Signed RPM list or common file directory missing. Contact the support."
+  log_error "Signed RPM list or common file directory is missing. Contact the support."
   exit $RESULT_ERROR
 }
 
@@ -29,7 +29,7 @@ grep -Hr "..*" $COMMON_DIR/default-*_obsoleted | sed -r "s|^$COMMON_DIR/([^:]+):
 [ ! -r "$ObsoletedPkgs" ] \
       || [ ! -r "$MoveObsoletedPkgs" ] \
       || [ ! -r "$NotBasePkgs" ] && {
-  log_error "Package content lists missing.  Contact the support."
+  log_error "Package content lists missing. Contact the support."
   rm -f "$ObsoletedPkgs" "$MoveObsoletedPkgs" "$NotBasePkgs"
   exit $RESULT_ERROR
 }
@@ -46,18 +46,18 @@ the packages are not replaced automatically.
 
 For some of the obsolete packages you will get the
 incompatibilities list from separate preupgrade
-modules and you can adjust your migration or upgrade
+modules, and you can adjust your migration or upgrade
 as required.
 
-Sometimes, the functionality of a package requires
+Sometimes the functionality of a package requires
 more than one new package to achieve the same
 functionality.
 
 Note: All packages from the debug repositories
-are skipped and Red Hat recommends that you remove
+are skipped, and Red Hat recommends that you remove
 them before upgrade.
 
-The following packages are obsolete and replaced by
+The following packages are obsolete, and replaced by
 new ones:" >solution.txt
 
 #Check for package obsolete type replacements in packages
@@ -85,7 +85,7 @@ do
   done
   [ -n "$req_pkgs" ] && {
     req_pkgs="${req_pkgs% }"
-    msg_req=" (required by Non Red Hat signed package(s):$req_pkgs)"
+    msg_req=" (required by packages not signed by Red Hat:$req_pkgs)"
     func_log_risk=log_high_risk
   }
   channel="$(grep "^$orig_pkg[[:space:]]" "$MoveObsoletedPkgs" | rev | cut -d "_" -f 1 | rev)"
@@ -103,13 +103,13 @@ do
   if [ $is_moved -eq 1 ] || [ $is_not_base -eq 1 ]; then
     # [ "$channel" == "optional" ] && optional=1 # unused variable
     other_repositories="${other_repositories}$channel "
-    msg_channel=" ($channel channel in RHEL 7)"
+    msg_channel=" ($channel channel in Red Hat Enterprise Linux 7)"
   fi
 
   # logs / prints
-  [ -n "$msg_req" ] && $func_log_risk "The package ${orig_pkg}$msg_req was removed between Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7"
-  [ $is_moved -eq 1 ] && $func_log_risk "The partial replacement for $orig_pkg moved to the $channel channel between Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7."
-  [ $is_not_base -eq 1 ] && $func_log_risk "The partial replacement for $orig_pkg is available in the $channel channel on Red Hat Enterprise Linux 7."
+  [ -n "$msg_req" ] && $func_log_risk "The package ${orig_pkg}$msg_req was removed between Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7."
+  [ $is_moved -eq 1 ] && $func_log_risk "The partial replacement for the $orig_pkg package moved to the $channel channel between Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7."
+  [ $is_not_base -eq 1 ] && $func_log_risk "The partial replacement for the $orig_pkg package is available in the $channel channel in Red Hat Enterprise Linux 7."
   echo "${orig_pkg}$msg_req was replaced by ${new_pkgs}$msg_channel" >>solution.txt
   {
     # store data to kickstart files
@@ -132,12 +132,12 @@ One or more replacement packages are available only in other repositories.
 If you want to install them later, you will need to attach subscriptions that provide:
 $repos_texts
 
-Then enable any equivalent repositories (if they are disabled) and install any needed packages.
+Then, enable any equivalent repositories (if they are disabled), and install any needed packages.
 For this purpose, run a prepared script:
 $_DST_NOAUTO_POSTSCRIPT <path/to/pkglist-file>
 
 which will install the available packages listed in the file.
-See ${KICKSTART_README} for details on 'pkglist' files.
+See ${KICKSTART_README} for the details on 'pkglist' files.
 " >>solution.txt
 }
 
@@ -151,20 +151,20 @@ done
 
 
   echo -n "
- * ${FILENAME_BASIS} - This file contains all Red Hat Enterprise Linux 6 packages which were replaced in Red Hat Enterprise Linux 7 by a not 100% compatible alternative and are a part of the base channel. Direct dependency from the packages not signed by Red Hat was not discovered.
- * ${FILENAME_BASIS}-required - Similar to ${FILENAME_BASIS}, but in addition are required by the packages not signed by Red Hat. As some of your packages depend on it, check the changes in detail.
- * ${FILENAME_BASIS}-notbase - Similar to ${FILENAME_BASIS}, but these packages are not a part of the base channel on Red Hat Enterprise Linux 7. Register the new machine and attach subscriptions with the correct repositories if you want to install them.
- * ${FILENAME_BASIS}-required-notbase - Similar to ${FILENAME_BASIS}-required and ${FILENAME_BASIS}-notbase - packages are required by the packages not signed by Red Hat and are not a part of the base channel.
+ * ${FILENAME_BASIS} - This file contains all Red Hat Enterprise Linux 6 packages that were replaced in Red Hat Enterprise Linux 7 by a not 100% compatible alternative, and that are a part of the Base channel. Direct dependency from the packages not signed by Red Hat was not discovered.
+ * ${FILENAME_BASIS}-required - Similar to ${FILENAME_BASIS}, but in addition these packages are required by the packages not signed by Red Hat. As some of your packages depend on it, check the changes in detail.
+ * ${FILENAME_BASIS}-notbase - Similar to ${FILENAME_BASIS}, but these packages are not a part of the Base channel in Red Hat Enterprise Linux 7. Register the new machine, and attach subscriptions with the correct repositories if you want to install them.
+ * ${FILENAME_BASIS}-required-notbase - Similar to ${FILENAME_BASIS}-required and ${FILENAME_BASIS}-notbase. The packages are required by the packages not signed by Red Hat, and they are not a part of the Base channel.
 " >> "$KICKSTART_README"
 
 echo \
 "
-If a package not signed by Red Hat requires these packages, you may need to check if the alternative solution provided by Red Hat works for you. You may need to get the missing package from a source other than the Red Hat Enterprise Linux repositories.
+If a package not signed by Red Hat requires these packages, you may need to check if an alternative solution provided by Red Hat works for you. You might need to get the missing package from a source other than the Red Hat Enterprise Linux repositories.
 
-You will need to install these new packages yourself after the assessment, as Red Hat cannot assess the suitablility of the replacements for your workload." >>solution.txt
+You will need to install these new packages yourself after the assessment, as Red Hat cannot assess the suitability of the replacements for your workload." >>solution.txt
 
 [ $found -eq 1 ] && log_medium_risk "\
-Some packages installed on the system were removed between Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7. This may break the functionality of the packages depending on them." && exit $RESULT_FAIL
+Some packages installed on the system were removed between Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7. This might break the functionality of the packages depending on them." && exit $RESULT_FAIL
 
 rm -f solution.txt && touch solution.txt
 
diff --git a/RHEL6_7/packages/RemovedPackages/check b/RHEL6_7/packages/RemovedPackages/check
--- a/RHEL6_7/packages/RemovedPackages/check
+++ b/RHEL6_7/packages/RemovedPackages/check
@@ -13,7 +13,7 @@ cat "$COMMON_DIR"/default*_removed* | grep -v "\.so" | cut -f1 -d' ' | sort | un
   exit $RESULT_ERROR
 
 [ ! -r "$RemovedPkgs" ] && \
-  log_error "Generic part of the content is missing." && \
+  log_error "Generic part of the module is missing." && \
   exit $RESULT_ERROR
 
 SCRIPT_NAME="postupgrade_cleanup.sh"
@@ -28,7 +28,7 @@ get_dist_native_list > $POSTUPGRADE_DIR/$(basename $VALUE_RPM_RHSIGNED)
 found=0
 rm -f solution.txt
 echo \
-"Some packages were removed between Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7. This may break
+"Some packages were removed between Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7. This might break
 the upgrade for some of your packages. We are not aware of any compatible
 replacement for these packages.
 
@@ -59,20 +59,20 @@ grep -v required solution.txt | grep -v " " | grep -v "^$" >> "$KICKSTART_DIR/Re
 grep required "$KICKSTART_DIR/RemovedPkg-required" >/dev/null || rm "$KICKSTART_DIR/RemovedPkg-required"
 grep [a-zA-Z] "$KICKSTART_DIR/RemovedPkg-optional" >/dev/null || rm "$KICKSTART_DIR/RemovedPkg-optional"
 [ -f "$KICKSTART_DIR/RemovedPkg-required" ] && \
-  echo " * RemovedPkg-required - This file contains all Red Hat Enterprise Linux 6 packages which were removed in Red Hat Enterprise Linux 7. There is no known compatible-enough alternative for them. As some of your packages depend on them, check the changes carefully." >>"$KICKSTART_README"
+  echo " * RemovedPkg-required - This file contains all Red Hat Enterprise Linux 6 packages that were removed in Red Hat Enterprise Linux 7. There is no known compatible-enough alternative for them. As some of your packages depend on them, check the changes carefully." >>"$KICKSTART_README"
 [ -f "$KICKSTART_DIR/RemovedPkg-optional" ] && \
-  echo " * RemovedPkg-optional - Similar to RemovedPkg-required, but in this case no package not signed by Red Hat requires this. It is more of an informational thing for you so that you can deal with the unavailability of these packages." >>"$KICKSTART_DIR/README"
+  echo " * RemovedPkg-optional - Similar to the RemovedPkg-required file, but in this case, no package not signed by Red Hat requires this. It is more of an informational thing for you, so that you can deal with the unavailability of these packages." >>"$KICKSTART_DIR/README"
 
 echo \
 "
 If a package not signed by Red Hat requires these packages, you may need to ask your
-vendor to provide an alternative solution or get the missing package from
-different sources than Red Hat Enterprise Linux.
+vendor to provide an alternative solution, or you may get the missing package from
+other sources than Red Hat Enterprise Linux.
 " >>solution.txt
-[ $found -eq 1 ] && log_high_risk "After upgrading to Red Hat Enterprise Linux 7 there are still some el6 packages left. Add --cleanup-post option to redhat-upgrade-tool if you want to remove them automatically."
+[ $found -eq 1 ] && log_high_risk "After upgrading to Red Hat Enterprise Linux 7, there are still some el6 packages left. Add the '--cleanup-post' option to redhat-upgrade-tool if you want to remove them automatically."
 
 [ $found -eq 1 ] && log_medium_risk "\
-We detected that some packages installed on the system were removed between Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7. This may break the functionality of the packages depending on them." && exit $RESULT_FAIL
+We detected that some packages installed on the system were removed between Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7. This might break the functionality of the packages that depend on the removed packages." && exit $RESULT_FAIL
 
 rm -f solution.txt && touch solution.txt
 
diff --git a/RHEL6_7/usrmgmt/ReservedIDs/check b/RHEL6_7/usrmgmt/ReservedIDs/check
--- a/RHEL6_7/usrmgmt/ReservedIDs/check
+++ b/RHEL6_7/usrmgmt/ReservedIDs/check
@@ -14,7 +14,7 @@ founderror=1
 }
 
 
-[ ! -r uidgid ] && log_error "Generic part of the content is missing!" && \
+[ ! -r uidgid ] && log_error "Generic part of the module is missing." && \
   exit $RESULT_ERROR
 
 founderror=0
@@ -22,7 +22,7 @@ rm solution.txt
 
 
 echo \
-"The packages might create system accounts with static IDs based on the reservation in the /usr/share/doc/setup-*/uidgid file. If you have any violations against the uidgid file reservation, the applications might not work properly, or they might cause some unexpected behaviour. As the reservations between different releases of Red Hat Enterprise Linux might differ, check carefully the findings below.
+"The packages might create system accounts with static IDs based on the reservation in the /usr/share/doc/setup-*/uidgid file. If you have any violations against the uidgid file reservation, the applications might not work properly, or they might cause some unexpected behavior. As the reservations between different releases of Red Hat Enterprise Linux might differ, check the findings below carefully.
 
 Especially the cases when an ID reserved by an application is used by a different account are really important. Using a different account than the reserved one might cause interoperability issues.
 " > solution.txt
@@ -78,9 +78,9 @@ fi
 done
 echo " These issues do not usually cause critical failures, but in rare cases they might contribute to some hard-to-analyze failures in the case where the system ID values are hard-coded in the application. " >> solution.txt
 
-[ $founderror -eq 1 ] &&  log_medium_risk "Reserved user and group IDs by setup package changed between Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7"; exit $RESULT_FAIL
+[ $founderror -eq 1 ] &&  log_medium_risk "Reserved user and group IDs by the setup package changed between Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7."; exit $RESULT_FAIL
 
 #no issues found, so remake solution text
 rm solution.txt
-echo \ "The packages might create system accounts with static IDs based on the reservation in the /usr/share/doc/setup-*/uidgid file. If you have any violations against the uidgid file reservation, the applications might not work properly or they might cause some unexpected behavior. In your case, no important divergence from the reservations was found. Even small findings (such as different login shells and application home directories) might be worth checking. See these in the warnings. Flaws in reserved IDs were not found on your system so this check passed, although the warnings might exist. " >solution.txt
+echo \ "The packages might create system accounts with static IDs based on the reservation in the /usr/share/doc/setup-*/uidgid file. If you have any violations against the uidgid file reservation, the applications might not work properly, or they might cause some unexpected behavior. In your case, no important divergence from the reservations was found. Even small findings (such as different login shells and application home directories) might be worth checking. See these in the warnings. Flaws in reserved IDs were not found on your system so this check passed, although the warnings might exist. " >solution.txt
 exit $RESULT_PASS
